-- ══════════════════════════════════════════════════════════════════════════
--  이 파일은 더 이상 스키마 파일이 아닙니다. 실행해도 아무 일도 일어나지 않습니다.
-- ══════════════════════════════════════════════════════════════════════════
--
--  왜 비웠나
--    예전 이 파일에는 users / markets / applications 를 DROP 하고 다시 만드는
--    구문이 들어 있었고, 데이터를 넣는 INSERT 는 하나도 없었습니다.
--    파일 이름이 "init_with_data" 라서 데이터가 들어 있을 것처럼 보였지만
--    실제로는 정반대로, 실행하는 순간 회원·마켓·신청 데이터가 전부 사라졌습니다.
--
--    실제로 이 사고가 났기 때문에, 가장 많이 눈에 띄는 이 파일에서
--    파괴적인 구문을 전부 걷어냈습니다. 이제 이 파일을 실수로 실행해도 안전합니다.
--
--  ▸ 스키마가 바뀌었을 때 (거의 모든 경우)
--      기존 데이터를 지우지 않고 컬럼만 추가/변경합니다.
--
--        cd backend
--        node scripts/migrate-add-swagger-columns.js
--        node scripts/migrate-add-auth-sessions.js
--        node scripts/migrate-add-user-profile-fields.js
--        node scripts/migrate-add-active-role.js
--        (scripts 폴더의 migrate-*.js 를 전부 실행하면 최신 스키마가 됩니다.
--         여러 번 실행해도 안전하게 만들어져 있습니다.)
--
--  ▸ 완전히 새 DB 를 처음 만들 때만
--        config/DANGER_DO_NOT_RUN_init_with_data.sql
--
--        이름 그대로 위험한 파일입니다. 비어 있는 DB 가 아니면
--        파일 안의 안전장치가 오류를 내고 스스로 멈춥니다.
--
--  ▸ 무엇이든 실행하기 전에 백업부터
--        mysqldump -u root -p flea_market_db > backup_20260731.sql
--
-- ══════════════════════════════════════════════════════════════════════════

SELECT '이 파일은 비어 있습니다. 스키마 변경은 backend/scripts/migrate-*.js 를 쓰세요.' AS 안내;
